/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface Task {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface _SERVICE {
  'addNote' : ActorMethod<[string, string], Note>,
  'addTask' : ActorMethod<[string, string], Task>,
  'clearHistory' : ActorMethod<[], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'sendMessage' : ActorMethod<[string], string>,
  'updateTaskStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];